name: pipeline
channels:
  - conda-forge
  - maxiv
dependencies:
  - python=3.11
  - pip
  - bitshuffle-python
  - h5py
  - scipy
  - h5pyd
  # testing dependencies
  - pytest
  # dranspose dependencies
  - pyzmq
  - redis-py
  - hiredis
  - fastapi
  - uvicorn
  - numpy
  - pydantic
  - pydantic-settings
  - jsonpath-ng
  - cbor2
  - redis-logs
  - pip:
    - dranspose==0.1.1
